_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
dataset:
    value:
        train_path: ../dataset/train
        val_path: ../dataset/val
model:
    value:
        name: vit-demo
        num_classes: 101
train:
    value:
        batch_size: 64
        lr: 0.01
        num_epochs: 10
